### ISSUE TITLE
WebSocket client + arraybuffer binaryType issue

### ISSUE THREAD

**Issue by endel** [stackblitz/webcontainer-core#1182]
### **Description of Bug**

The WebSocket client doesn't seem to be receiving the payload correctly when using `.binaryType = "arraybuffer"`.

https://stackblitz.com/edit/stackblitz-starters-uuauht?file=public%2Findex.html

### **Steps to Reproduce**

1. Start the http/ws server
2. Open the "/" URL in the browser
3. See the console logs on the browser's Developer Tools
4. You will notice that received bytes differ depending on the `binaryType` used (`"blob"` receives correctly, whereas `"arraybuffer"` seems to be receiving additional bytes)

```
Received bytes (arraybuffer): [130, 1, 10]
Received bytes (blob): [10]
```

### **Expected Behavior**

Both WebSocket client connections should be receiving the exact data sent by the server (`[10]`)

```
Received bytes (arraybuffer): [10]
Received bytes (blob): [10]
```

### **Screenshots/Screencast**

![Screenshot 2023-09-15 at 16 13 13](https://github.com/stackblitz/core/assets/130494/bff915cf-c884-4bf6-8d55-14cb5429ebf7)

**Comment by Nemikolh** [comment]
Hi @endel ! Thank you so much for the minimal reproduction link! :star2: Super cool :smiley: 

We'll investigate, our support for `arraybuffer` might be buggy.

I'll keep you posted!

**Comment by terry-fei** [comment]
https://github.com/websockets/ws/issues/1175
It might be helpful

**Comment by remocons** [comment]
It has been 10 months. Please resolve this issue quickly.

**Comment by jjmalovich2** [comment]
Lock in, multiplayer is hard to develop with this bug

**Comment by SamVerschueren** [comment]
I'm currently looking into this one. I might've found something. I'll keep you posted.

**Comment by SamVerschueren** [comment]
I have a fix which is in review. We will wait until monday to release this but I'll keep you posted once that's done. Sorry for the delay, it's been a bit hectic 🙈 .

**Comment by endel** [comment]
That's great news, thank you for the update!

**Comment by SamVerschueren** [comment]
I believe the issue should be solved now. The fix has been deployed but not at my computer so can't double check right now.

**Comment by endel** [comment]
Hi @SamVerschueren, I've just tried loading the example project I've made in [September 2023](https://stackblitz.com/edit/stackblitz-starters-uuauht?file=public%2Findex.html) and I'm still seeing the same output from the browser's console:

![Image](https://github.com/user-attachments/assets/9442a606-d5cc-4b47-9f6f-89edca74d422)

It is possible to specify to use the newer version of webcontainer-core in that project, or is the newer version grabbed automatically even for projects created previously?

Thank you for taking a look at this. 🙏

**Comment by SamVerschueren** [comment]
Oh I already know why it doesn't work. Can you try adding a `engines.node` field to your package.json file and specify "20" as value. More info here https://github.com/stackblitz/webcontainer-core/issues/560#issuecomment-2760594533

Currently the default Node version is 18 and will very soon become 20. I forgot to back port this to 18 so it's currently only available in 20. I'll fix that tomorrow.

For now you can use the workaround by explicitly requesting 20 as the version.
