### ISSUE TITLE
Editor not at latest version of TypeScript

### ISSUE THREAD

**Issue by davidkpiano** [stackblitz/webcontainer-core#1485]
### Describe the bug

The StackBlitz editor's TypeScript version has two problems (or maybe one problem, depending on perspective):

- It lags behind the latest stable TypeScript version
- It does not use the installed TypeScript version

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-faphes?file=src%2Fmain.ts,package.json&terminal=dev

### Steps to reproduce

1. Go to `main.ts`
2. Observe the TypeScript errors

### Expected behavior

There are no TypeScript errors, since the editor should be running on the latest stable version of TypeScript

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="458" alt="Screenshot 2024-07-11 at 9 38 40 AM" src="https://github.com/stackblitz/webcontainer-core/assets/1093738/8291ad85-454e-4bbd-823a-3afd095d9b7b">

### Platform

```
Browser name  = Chrome
Full version  = 125.0.0.0
Major version = 125
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 203022543,
  "usedJSHeapSize": 193694363,
  "jsHeapSizeLimit": 4294705152
}
Hash = 70dbe416
```

**Comment by SamVerschueren** [comment]
Hey @davidkpiano 👋 ! Thanks for reaching out. This is now fixed and it is using the latest TypeScript 5.5.3.

**Comment by davidkpiano** [comment]
Thank you! I'm still seeing the type error though: https://stackblitz.com/~/edit/vitejs-vite-faphes?file=src/main.ts:L30!,package.json&terminal=dev

<img width="401" alt="CleanShot 2024-07-15 at 08 43 53@2x" src="https://github.com/user-attachments/assets/6b695e47-dcee-4e14-8e8a-c3486c8d7b97">

**Comment by SamVerschueren** [comment]
Oh gotcha. I noticed now that you are using Codeflow which uses 5.4.5 as the default. If you do `> Select TypeScript version` and pick `Use workspace version`, that should address the issue (at least it did that for me).

The version we now updated was on the [classic editor](https://stackblitz.com/c/edit/vitejs-vite-faphes?file=src/main.ts:L30!,package.json&terminal=dev).
