### ISSUE TITLE
RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance

### ISSUE THREAD

**Issue by Lonli-Lokli** [stackblitz/webcontainer-core#908]
### Describe the bug

I am trying to use Nx+Angular with WebContainer but it does not work

### Link to the blitz that caused the error

https://stackblitz.com/edit/nx-standalone-angular?file=decorate-angular-cli.js&preset=node

### Steps to reproduce

1. Open link
2. Wait for running node ./decorate-angular-cli.js
3. Open DevTools, wait for 2 minutes until a lot of wasm libraries loaded
4. Failed with error 
       
       Uncaught (in promise) RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance

### Expected behavior

No errors

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: Windows
- Browser: Edge
- Version: 107.0.1418.56 (Official build) (64-bit)

**Comment by OriginalEXE** [comment]
We are experiencing the same issue with our Next.js projects, example here: https://stackblitz.com/edit/uniformdev-uniformconf-6jayu8?file=next.config.js

The initial route sometimes successfully renders, but subsequent navigation consistently triggers the error.

Playing around with npm dependencies unfortunately didn't help.

**Comment by d3lm** [comment]
Thanks for reporting this issue 🙏 Do you happen to have multiple projects open at the same time?

Also, I can't run the project that was linked because I am getting `Cannot find project 'ng-app'`. Can you try and update the project so that it works and that I can try and reproduce the OOM issue?

@OriginalEXE I can't seem to reproduce the OOM issue on my end, but I also have 32 GB of memory, which may help. How much memory does your machine have?

**Comment by OriginalEXE** [comment]
Hi @d3lm, I also have 32GB, but can no longer reproduce the issue either, so whatever it was got fixed in the meantime which is great :)

**Comment by Lonli-Lokli** [comment]
My original url completely frozing my computer, assuming it is just loading all my 16gb plus disk for heap.

I honestly not sure what is worse - broken repro for those who have 32gb or website which requires more than 16gb memory to run 
![16775892572577124120147814934196](https://user-images.githubusercontent.com/767795/221861281-c30881fd-0adf-4990-b813-6cc9230cc291.jpg)

**Comment by d3lm** [comment]
@Lonli-Lokli I am still getting `Cannot find project 'ng-app'` and I can't test the project. Can you please provide a link that reproduces the OOM? If you think the error is another issue, please file a separate report.

**Comment by Lonli-Lokli** [comment]
I will try to run it, have to buy more memory

**Comment by Lonli-Lokli** [comment]
@d3lm Can you please recheck my original URL? I hope I fixed this issue, but now my Edge instance just crashes

**Comment by d3lm** [comment]
I tried your link and it still doesn't work as files are missing:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/12571019/227174204-c36ba269-c9ec-499c-aa94-f4f8609345b5.png">

Also, WebContainer does not consume 16 GB of RAM. For larger projects, I can see the whole memory consumption peaks at ~2GB maybe which is a lot but it's far from 16 GB.

**Comment by Lonli-Lokli** [comment]
@d3lm can you recheck again? I still see OOM with tab crash.

It is not smth which stays long, but I captured it - it goes up very quickly from 300mb to 1gb and 7gb. I am not not sure that Browser Process Manager could handle it so quickly
<img width="718" alt="image" src="https://user-images.githubusercontent.com/767795/227177855-66a915d0-c52d-4dd4-a889-c2d5a67170c8.png">

**Comment by d3lm** [comment]
Hmm, I tried in MS Edge and I am seeing it goes up to 2 GB and then it drops again a little.

**Comment by Lonli-Lokli** [comment]
So now you can open my URL and no tab crash right, application is running?

**Comment by OriginalEXE** [comment]
For me it bursts up to 4.7 GB in Brave, but then falls to 2.9 GB. No crash, but the app is not running because I get

> Cannot find module '/home/projects/nx-standalone-angular/@nrwl/react/plugins/webpack'

**Comment by Lonli-Lokli** [comment]
@d3lm do you observe the same error as @OriginalEXE ?

**Comment by Thy3634** [comment]
I believe it is a bug of chromium, because edge chromium and chrome crash, and firefox is fine.

**Comment by channyeintun** [comment]
This happens on my Chrome as well. 

Vite: Version 8.1.0
Chrome: Version 150.0.7871.47 (Official Build) (arm64)
